// <auto-generated />
namespace ProjectManager.Infrastructure.Persistance
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CombineNotificationsAndTasks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CombineNotificationsAndTasks));
        
        string IMigrationMetadata.Id
        {
            get { return "202406201509330_CombineNotificationsAndTasks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
