// <auto-generated />
namespace ProjectManager.Infrastructure.Persistance
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_photoPath_In_Projects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_photoPath_In_Projects));
        
        string IMigrationMetadata.Id
        {
            get { return "202405200708343_add_photoPath_In_Projects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
